### ISSUE TITLE
gitignore

### ISSUE THREAD

**Issue by Burtt** [FRC-Team-3242/Pre-Season-2017#1]
The "dist" and "build" directories should be added to the gitignore file. Generally, only source code should be included in repositories, not compiled code or dependencies, which is what these folders contain.

Edit: The dependencies (the "dist" folder) should probably actually stay in this case though, since the FRC plugins for eclipse can be wonky.

**Comment by gabrielflechas** [comment]
In that case, we should probably add the "bin" directory as well, right? IIRC that is the one that contains the complied code (although it seems like the "build" directory does too?). I'm pretty sure that re-compiles automatically whenever it is deployed to the robot, so it shouldn't be an issue.

**Comment by Burtt** [comment]
The "bin" directory is actually already in the gitignore file. I'm not really sure why there's both a bin and a build directory; after looking around in them, they seem to contain nearly exactly the same files. It's not a big deal, the plugins will just recompile every time anyways, but there's really no reason to have git track the build files.
